"""Add identity defaults to primary keys

Revision ID: a7b3c9d4e5f6
Revises: 62ea25842e8a
Create Date: 2026-04-26 08:00:00.000000

"""
from typing import Sequence, Union

from alembic import op


revision: str = "a7b3c9d4e5f6"
down_revision: Union[str, None] = "62ea25842e8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TABLES = [
    "app_settings",
    "businesses",
    "categories",
    "inventory_movements",
    "product_barcodes",
    "products",
    "sale_items",
    "sale_payments",
    "sales",
    "stock_balances",
    "stores",
    "users",
    "external_product_cache",
]


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS external_product_cache (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            barcode VARCHAR NOT NULL UNIQUE,
            source VARCHAR NOT NULL,
            product_name TEXT NULL,
            brand VARCHAR NULL,
            image_url TEXT NULL,
            category_name VARCHAR NULL,
            raw_response JSON NULL,
            last_fetched_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
            expires_at TIMESTAMP WITH TIME ZONE NOT NULL
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_external_product_cache_barcode "
        "ON external_product_cache (barcode)"
    )

    for table in TABLES:
        op.execute(
            f"""
            DO $$
            DECLARE
                seq_name text;
            BEGIN
                IF to_regclass('{table}') IS NULL THEN
                    RETURN;
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_attribute a
                    JOIN pg_class c ON c.oid = a.attrelid
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                    WHERE c.relname = '{table}'
                      AND n.nspname = current_schema()
                      AND a.attname = 'id'
                      AND a.attidentity <> ''
                )
                AND NOT EXISTS (
                    SELECT 1
                    FROM pg_attrdef d
                    JOIN pg_attribute a ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                    JOIN pg_class c ON c.oid = d.adrelid
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                    WHERE c.relname = '{table}'
                      AND n.nspname = current_schema()
                      AND a.attname = 'id'
                )
                THEN
                    EXECUTE 'ALTER TABLE {table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
                END IF;

                seq_name := pg_get_serial_sequence('{table}', 'id');
                IF seq_name IS NOT NULL THEN
                    EXECUTE format(
                        'SELECT setval(%L, COALESCE((SELECT MAX(id) FROM {table}), 0) + 1, false)',
                        seq_name
                    );
                END IF;
            END $$;
            """
        )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_external_product_cache_barcode")
    op.execute("DROP TABLE IF EXISTS external_product_cache")

    for table in reversed(TABLES):
        op.execute(
            f"""
            DO $$
            BEGIN
                IF to_regclass('{table}') IS NOT NULL
                AND EXISTS (
                    SELECT 1
                    FROM pg_attribute a
                    JOIN pg_class c ON c.oid = a.attrelid
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                    WHERE c.relname = '{table}'
                      AND n.nspname = current_schema()
                      AND a.attname = 'id'
                      AND a.attidentity <> ''
                )
                THEN
                    EXECUTE 'ALTER TABLE {table} ALTER COLUMN id DROP IDENTITY IF EXISTS';
                END IF;
            END $$;
            """
        )
